[package]
name = "rulelib"
version = "0.0.1"
edition = "2021"
authors = ["TOwInOK"]
license = "MIT"


[dependencies]
reqwest = { version = "0.12.5", features = ["json"] }
serde = { version = "1.0.203", features = ["derive"] }
tokio = { version = "1.38.0", features = ["macros"] }
