name: CI/CD Rust -> Check code and push to crates.io

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Type of version increment'
        required: true
        default: 'patch'
        options:
          - patch # 1.0.0 -> 1.0.1
          - minor # 1.0.0 -> 1.1.0
          - major # 1.0.0 -> 2.0.0

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v4
    
    - name: Use cached deps
      uses: actions/cache@v4
      with: 
        path: target/release
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Configurate rust
      uses: actions-rs/toolchain@v1.0.6
      with: 
          toolchain: stable
      
    - name: clippy
      run: cargo clippy --all-targets -F full -r -- -D warnings

    # Test all code by parts
    
    - name: Test code
      run: cargo test -p shuller -F full -r --lib;

    - name: Test code and tests
      run: cargo test -p shuller tests -F full -r;

    - name: Tests doc
      run: cargo test -F full --doc -r
      
    - name: Build
      run: cargo build -F full -r

    - name: Publish to crates.io
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        EVENT_TYPE: ${{ github.event.inputs.version_type }}
      run: | 
        cargo install cargo-release
        cargo publish $EVENT_TYPE --publish --token $CARGO_REGISTRY_TOKEN -- -F full --color=always

      
